run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - exportloopref
    - gocritic
    - gocyclo
    - dupl
    - misspell

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  gocritic:
    enabled-checks:
      - appendCombine
      - dupBranchBody
      - emptyFallthrough
      - evalOrder
      - ifElseChain
      - unnecessaryBlock
      - weakCond

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

